[package]
name = "vnlang-rust"
version = "0.1.0"

[lib]
name = "vnlang_lib"
path = "lib/vnlang.rs"

[[bin]]
name = "vnlang_repl"
path = "repl/main.rs"

[[bin]]
name = "vnlang_exe"
path = "src/main.rs"

[dependencies]
nom = "^4.0.0"
clap = "~2.31.2"
rustyline = "~6.0.0"
